// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface StepperCard {
  id: number;
  attributes: {
    cardTitle: string;
    imageLeftOne: { data: Media };
    imageLeftTwo: { data: Media };
    imageRight?: { data: Media };
    cardIcon: { data: Media };
    cardText: string;
    slug?: string;
  };
}
export interface StepperCard_Plain {
  id: number;
  cardTitle: string;
  imageLeftOne: Media;
  imageLeftTwo: Media;
  imageRight?: Media;
  cardIcon: Media;
  cardText: string;
  slug?: string;
}

export interface StepperCard_NoRelations {
  id: number;
  cardTitle: string;
  imageLeftOne: number;
  imageLeftTwo: number;
  imageRight?: number;
  cardIcon: number;
  cardText: string;
  slug?: string;
}

export interface StepperCard_AdminPanelLifeCycle {
  id: number;
  cardTitle: string;
  imageLeftOne: AdminPanelRelationPropertyModification<Media>;
  imageLeftTwo: AdminPanelRelationPropertyModification<Media>;
  imageRight?: AdminPanelRelationPropertyModification<Media>;
  cardIcon: AdminPanelRelationPropertyModification<Media>;
  cardText: string;
  slug?: string;
}
