// Interface automatically generated by schemas-to-ts

export interface PrivacyPolicy {
  id: number;
  attributes: {
    titlePage?: string;
    content?: string;
  };
}
export interface PrivacyPolicy_Plain {
  id: number;
  titlePage?: string;
  content?: string;
}

export interface PrivacyPolicy_NoRelations {
  id: number;
  titlePage?: string;
  content?: string;
}

export interface PrivacyPolicy_AdminPanelLifeCycle {
  id: number;
  titlePage?: string;
  content?: string;
}
