// Interface automatically generated by schemas-to-ts

import { Author } from '../../../../components/blocks/interfaces/Author';
import { Tag } from '../../../../components/blocks/interfaces/Tag';
import { Service } from '../../../service/content-types/service/service';
import { Author_Plain } from '../../../../components/blocks/interfaces/Author';
import { Tag_Plain } from '../../../../components/blocks/interfaces/Tag';
import { Service_Plain } from '../../../service/content-types/service/service';
import { Author_NoRelations } from '../../../../components/blocks/interfaces/Author';
import { Tag_NoRelations } from '../../../../components/blocks/interfaces/Tag';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Testimonial {
  id: number;
  attributes: {
    rank?: number;
    title?: string;
    slug?: string;
    author?: Author;
    tags: Tag[];
    service?: { data: Service };
  };
}
export interface Testimonial_Plain {
  id: number;
  rank?: number;
  title?: string;
  slug?: string;
  author?: Author_Plain;
  tags: Tag_Plain[];
  service?: Service_Plain;
}

export interface Testimonial_NoRelations {
  id: number;
  rank?: number;
  title?: string;
  slug?: string;
  author?: Author_NoRelations;
  tags: Tag_NoRelations[];
  service?: number;
}

export interface Testimonial_AdminPanelLifeCycle {
  id: number;
  rank?: number;
  title?: string;
  slug?: string;
  author?: Author_Plain;
  tags: Tag_Plain[];
  service?: AdminPanelRelationPropertyModification<Service_Plain>;
}
