// Interface automatically generated by schemas-to-ts

export interface Author {
  name: string;
  position: string;
}
export interface Author_Plain {
  name: string;
  position: string;
}

export interface Author_NoRelations {
  name: string;
  position: string;
}

