// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Guidelines {
  title: string;
  description: string;
  picture: { data: Media };
}
export interface Guidelines_Plain {
  title: string;
  description: string;
  picture: Media;
}

export interface Guidelines_NoRelations {
  title: string;
  description: string;
  picture: number;
}

