// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Images {
  image?: { data: Media };
}
export interface Images_Plain {
  image?: Media;
}

export interface Images_NoRelations {
  image?: number;
}

