// Interface automatically generated by schemas-to-ts

import { Text } from './Text';
import { Text_Plain } from './Text';
import { Text_NoRelations } from './Text';

export interface Issue {
  problem: Text[];
  solution: Text[];
}
export interface Issue_Plain {
  problem: Text_Plain[];
  solution: Text_Plain[];
}

export interface Issue_NoRelations {
  problem: Text_NoRelations[];
  solution: Text_NoRelations[];
}

