// Interface automatically generated by schemas-to-ts

export interface Link {
  linkTitle: string;
  linkSrc: string;
}
export interface Link_Plain {
  linkTitle: string;
  linkSrc: string;
}

export interface Link_NoRelations {
  linkTitle: string;
  linkSrc: string;
}

