// Interface automatically generated by schemas-to-ts

import { Tag } from './Tag';
import { Link } from './Link';
import { Tag_Plain } from './Tag';
import { Link_Plain } from './Link';
import { Tag_NoRelations } from './Tag';
import { Link_NoRelations } from './Link';

export interface Overview {
  tags: Tag[];
  dateCase: Date;
  title: string;
  link?: Link;
}
export interface Overview_Plain {
  tags: Tag_Plain[];
  dateCase: Date;
  title: string;
  link?: Link_Plain;
}

export interface Overview_NoRelations {
  tags: Tag_NoRelations[];
  dateCase: Date;
  title: string;
  link?: Link_NoRelations;
}

