// Interface automatically generated by schemas-to-ts

import { Author } from './Author'
import { Tag } from './Tag'
import { Author_Plain } from './Author'
import { Tag_Plain } from './Tag'
import { Author_NoRelations } from './Author'
import { Tag_NoRelations } from './Tag'

export interface Testimonial {
  title?: string;
  author?: Author;
  tags: Tag[];
}
export interface Testimonial_Plain {
  title?: string;
  author?: Author_Plain;
  tags: Tag_Plain[];
}

export interface Testimonial_NoRelations {
  title?: string;
  author?: Author_NoRelations;
  tags: Tag_NoRelations[];
}
