// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Service } from '../../../service/content-types/service/service';
import { Service_Plain } from '../../../service/content-types/service/service';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface DevStage {
  id: number;
  attributes: {
    icon: { data: Media };
    title: string;
    description: string;
    service?: { data: Service };
    slug?: string;
  };
}
export interface DevStage_Plain {
  id: number;
  icon: Media;
  title: string;
  description: string;
  service?: Service_Plain;
  slug?: string;
}

export interface DevStage_NoRelations {
  id: number;
  icon: number;
  title: string;
  description: string;
  service?: number;
  slug?: string;
}

export interface DevStage_AdminPanelLifeCycle {
  id: number;
  icon: AdminPanelRelationPropertyModification<Media>;
  title: string;
  description: string;
  service?: AdminPanelRelationPropertyModification<Service_Plain>;
  slug?: string;
}
