// Interface automatically generated by schemas-to-ts

import { ServiceCategory } from '../../../service-category/content-types/service-category/service-category';
import { Testimonial } from '../../../testimonial/content-types/testimonial/testimonial';
import { DevStage } from '../../../dev-stage/content-types/dev-stage/dev-stage';
import { ServiceCategory_Plain } from '../../../service-category/content-types/service-category/service-category';
import { Testimonial_Plain } from '../../../testimonial/content-types/testimonial/testimonial';
import { DevStage_Plain } from '../../../dev-stage/content-types/dev-stage/dev-stage';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Service {
  id: number;
  attributes: {
    title?: string;
    content?: any;
    service_category?: { data: ServiceCategory };
    testimonials: { data: Testimonial[] };
    dev_stages: { data: DevStage[] };
  };
}
export interface Service_Plain {
  id: number;
  title?: string;
  content?: any;
  service_category?: ServiceCategory_Plain;
  testimonials: Testimonial_Plain[];
  dev_stages: DevStage_Plain[];
}

export interface Service_NoRelations {
  id: number;
  title?: string;
  content?: any;
  service_category?: number;
  testimonials: number[];
  dev_stages: number[];
}

export interface Service_AdminPanelLifeCycle {
  id: number;
  title?: string;
  content?: any;
  service_category?: AdminPanelRelationPropertyModification<ServiceCategory_Plain>;
  testimonials: AdminPanelRelationPropertyModification<Testimonial_Plain>[];
  dev_stages: AdminPanelRelationPropertyModification<DevStage_Plain>[];
}
