// Interface automatically generated by schemas-to-ts

import { Service } from '../../../service/content-types/service/service';
import { Service_Plain } from '../../../service/content-types/service/service';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ServiceCategory {
  id: number;
  attributes: {
    name: string;
    slug?: string;
    description?: string;
    rank?: number;
    services: { data: Service[] };
  };
}
export interface ServiceCategory_Plain {
  id: number;
  name: string;
  slug?: string;
  description?: string;
  rank?: number;
  services: Service_Plain[];
}

export interface ServiceCategory_NoRelations {
  id: number;
  name: string;
  slug?: string;
  description?: string;
  rank?: number;
  services: number[];
}

export interface ServiceCategory_AdminPanelLifeCycle {
  id: number;
  name: string;
  slug?: string;
  description?: string;
  rank?: number;
  services: AdminPanelRelationPropertyModification<Service_Plain>[];
}
