// Interface automatically generated by schemas-to-ts

import { Images } from '../../../../components/blocks/interfaces/Images';
import { PortfolioCategory } from '../../../portfolio-category/content-types/portfolio-category/portfolio-category';
import { Overview } from '../../../../components/blocks/interfaces/Overview';
import { Issue } from '../../../../components/blocks/interfaces/Issue';
import { Guidelines } from '../../../../components/blocks/interfaces/Guidelines';
import { Images_Plain } from '../../../../components/blocks/interfaces/Images';
import { PortfolioCategory_Plain } from '../../../portfolio-category/content-types/portfolio-category/portfolio-category';
import { Overview_Plain } from '../../../../components/blocks/interfaces/Overview';
import { Issue_Plain } from '../../../../components/blocks/interfaces/Issue';
import { Guidelines_Plain } from '../../../../components/blocks/interfaces/Guidelines';
import { Images_NoRelations } from '../../../../components/blocks/interfaces/Images';
import { Overview_NoRelations } from '../../../../components/blocks/interfaces/Overview';
import { Issue_NoRelations } from '../../../../components/blocks/interfaces/Issue';
import { Guidelines_NoRelations } from '../../../../components/blocks/interfaces/Guidelines';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface PortfolioCase {
  id: number;
  attributes: {
    title?: string;
    description?: any;
    images: Images[];
    portfolio_category?: { data: PortfolioCategory };
    slug?: string;
    subtitle?: string;
    overviewCase?: Overview;
    clientCase?: any;
    issueCase?: Issue;
    guidelines: Guidelines[];
    fullScreenImages: Images[];
  };
}
export interface PortfolioCase_Plain {
  id: number;
  title?: string;
  description?: any;
  images: Images_Plain[];
  portfolio_category?: PortfolioCategory_Plain;
  slug?: string;
  subtitle?: string;
  overviewCase?: Overview_Plain;
  clientCase?: any;
  issueCase?: Issue_Plain;
  guidelines: Guidelines_Plain[];
  fullScreenImages: Images_Plain[];
}

export interface PortfolioCase_NoRelations {
  id: number;
  title?: string;
  description?: any;
  images: Images_NoRelations[];
  portfolio_category?: number;
  slug?: string;
  subtitle?: string;
  overviewCase?: Overview_NoRelations;
  clientCase?: any;
  issueCase?: Issue_NoRelations;
  guidelines: Guidelines_NoRelations[];
  fullScreenImages: Images_NoRelations[];
}

export interface PortfolioCase_AdminPanelLifeCycle {
  id: number;
  title?: string;
  description?: any;
  images: Images_Plain[];
  portfolio_category?: AdminPanelRelationPropertyModification<PortfolioCategory_Plain>;
  slug?: string;
  subtitle?: string;
  overviewCase?: Overview_Plain;
  clientCase?: any;
  issueCase?: Issue_Plain;
  guidelines: Guidelines_Plain[];
  fullScreenImages: Images_Plain[];
}
