// Interface automatically generated by schemas-to-ts

export interface Category {
  id: number;
  attributes: {
    name: string;
    slug?: string;
    rank?: number;
  };
}
export interface Category_Plain {
  id: number;
  name: string;
  slug?: string;
  rank?: number;
}

export interface Category_NoRelations {
  id: number;
  name: string;
  slug?: string;
  rank?: number;
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  name: string;
  slug?: string;
  rank?: number;
}
