// Interface automatically generated by schemas-to-ts

import { PortfolioCase } from '../../../portfolio-case/content-types/portfolio-case/portfolio-case';
import { PortfolioCase_Plain } from '../../../portfolio-case/content-types/portfolio-case/portfolio-case';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface PortfolioCategory {
  id: number;
  attributes: {
    title?: string;
    slug?: string;
    portfolio_cases: { data: PortfolioCase[] };
  };
}
export interface PortfolioCategory_Plain {
  id: number;
  title?: string;
  slug?: string;
  portfolio_cases: PortfolioCase_Plain[];
}

export interface PortfolioCategory_NoRelations {
  id: number;
  title?: string;
  slug?: string;
  portfolio_cases: number[];
}

export interface PortfolioCategory_AdminPanelLifeCycle {
  id: number;
  title?: string;
  slug?: string;
  portfolio_cases: AdminPanelRelationPropertyModification<PortfolioCase_Plain>[];
}
